server:
  use-forward-headers: true

flyway:
  baseline-on-migrate: true
spring:

  application:
    name: DocShare
  
  profiles:
    active: #spring.profiles.active#

  datasource:
    #url: jdbc:mysql://localhost:3306/docshare
    url: jdbc:mysql://localhost:3306/mandua
    username: root
    password: nirvana3
    validationQuery: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-on-borrow: true
      max-active: 50
      
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: NON_NULL
  
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    open-in-view: false
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

security:
  user:
    password: password
  oauth2:
    resource:
      filter-order: 3
app:
  version: 0.0.1
  description: An simple app to share files easily!
  allowedOrigin: "http://localhost:4200"
